In [3]:
import pandas as pd

samples = pd.read_csv("../data/s_MTBLS2550.txt", sep="\t")

print(samples.shape)
samples.head(1)

(166, 43)

,Source Name,Characteristics[Organism],Term Source REF,Term Accession Number,Characteristics[Organism part],Term Source REF.1,Term Accession Number.1,Characteristics[Variant],Term Source REF.2,Term Accession Number.2,...,Term Accession Number.9,Factor Value[HER2 status],Term Source REF.10,Term Accession Number.10,Factor Value[Intercurrent tumors],Term Source REF.11,Term Accession Number.11,Factor Value[Breed],Term Source REF.12,Term Accession Number.12
0,16K-008,Canis lupus familiaris,NCBITAXON,http://purl.obolibrary.org/obo/NCBITaxon_9615,urine,BTO,http://purl.obolibrary.org/obo/BTO_0001419,Chihuahua,NCIT,http://purl.obolibrary.org/obo/NCIT_C53929,...,http://purl.obolibrary.org/obo/NCIT_C15492,Positive,NCIT,http://purl.obolibrary.org/obo/NCIT_C68748,simple carcinoma (grade 1),NaN,NaN,Chihuahua,NaN,NaN

In [4]:
samples.columns

Index(['Source Name', 'Characteristics[Organism]', 'Term Source REF',
       'Term Accession Number', 'Characteristics[Organism part]',
       'Term Source REF.1', 'Term Accession Number.1',
       'Characteristics[Variant]', 'Term Source REF.2',
       'Term Accession Number.2', 'Characteristics[Sample type]',
       'Term Source REF.3', 'Term Accession Number.3', 'Protocol REF',
       'Sample Name', 'Factor Value[Sex]', 'Term Source REF.4',
       'Term Accession Number.4', 'Factor Value[Tumor state]',
       'Term Source REF.5', 'Term Accession Number.5',
       'Factor Value[Tumor grade]', 'Term Source REF.6',
       'Term Accession Number.6', 'Factor Value[Age]', 'Unit',
       'Term Source REF.7', 'Term Accession Number.7',
       'Factor Value[Neutral Status]', 'Term Source REF.8',
       'Term Accession Number.8', 'Factor Value[ER status]',
       'Term Source REF.9', 'Term Accession Number.9',
       'Factor Value[HER2 status]', 'Term Source REF.10',
       'Term Accession Number.10', 'Factor Value[Intercurrent tumors]',
       'Term Source REF.11', 'Term Accession Number.11', 'Factor Value[Breed]',
       'Term Source REF.12', 'Term Accession Number.12'],
      dtype='str')

In [5]:
metabolites = pd.read_csv(
    "../data/m_MTBLS2550_NMR_CrAdj_metabolite_profiling_v2_maf.tsv",
    sep="\t"
)

print(metabolites.shape)
metabolites.head()

(56, 184)

,database_identifier,chemical_formula,smiles,inchi,metabolite_identification,chemical_shift,multiplicity,taxid,species,database,...,N-46_CrAdj,N-47_CrAdj,N-48_CrAdj,N-49_CrAdj,N-5_CrAdj,N-50_CrAdj,N-6_CrAdj,N-7_CrAdj,N-8_CrAdj,N-9_CrAdj
0,CHEBI:16797,C7H9N2O+,C[n+]1cccc(c1)C(N)=O,InChI=1S/C7H8N2O/c1-9-4-2-3-6(5-9)7(8)10/h2-5H...,1-Methylnicotinamide,"4.468(s), 8.172(m), 8.89(d), 8.97(d), 9.28(s)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,62.347629,61.097004,73.359667,44.949733,323.732306,60.390361,9.809516,28.084559,245.666184,1.664852
1,CHEBI:1148,C4H8O3,CCC(O)C(O)=O,"InChI=1S/C4H8O3/c1-2-3(5)4(6)7/h3,5H,2H2,1H3,(...",2-Hydroxybutyrate,"0.904 (t), 1.658 (m), 1.738 (m), 4.006(m)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,5.745055,3.118573,4.635981,3.139404,9.317327,6.499133,35.379473,59.429839,32.092595,7.451337
2,CHEBI:50129,C4H8O3,CC(C)(O)C(O)=O,"InChI=1S/C4H8O3/c1-4(2,7)3(5)6/h7H,1-2H3,(H,5,6)",2-Hydroxyisobutyrate,1.35(S),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,7.970999,6.478522,8.207578,6.659892,16.081347,7.262524,7.853047,12.433092,12.205708,3.329704
3,CHEBI:48430,C6H10O3,CC(C)CC(=O)C(O)=O,"InChI=1S/C6H10O3/c1-4(2)3-5(7)6(8)9/h4H,3H2,1-...",2-Oxoisocaproate,"0.9(d), 2.60(d)",NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,NaN,0.202756,1.951370,1.106958,1.478230,1.114137,4.293362,4.124602,3.840589,0.539952
4,CHEBI:48526,C9H10O2,CC(C(O)=O)c1ccccc1,InChI=1S/C9H10O2/c1-7(9(10)11)8-5-3-2-4-6-8/h2...,2-Phenylpropionate,1.397 (d),NaN,NCBI:txid9615,Canis lupus familiaris,800 MHz library of Chenomx NMR Suite,...,1.886752,1.071708,2.944794,NaN,4.031536,2.063217,10.679058,1.329697,5.813495,4.886565

In [6]:
metabolites.columns.value_counts

<bound method IndexOpsMixin.value_counts of Index(['database_identifier', 'chemical_formula', 'smiles', 'inchi',
       'metabolite_identification', 'chemical_shift', 'multiplicity', 'taxid',
       'species', 'database',
       ...
       'N-46_CrAdj', 'N-47_CrAdj', 'N-48_CrAdj', 'N-49_CrAdj', 'N-5_CrAdj',
       'N-50_CrAdj', 'N-6_CrAdj', 'N-7_CrAdj', 'N-8_CrAdj', 'N-9_CrAdj'],
      dtype='str', length=184)>

In [7]:
cols_importantes = [
    'Source Name',
    'Factor Value[Sex]',
    'Factor Value[Tumor state]',
    'Factor Value[Tumor grade]',
    'Factor Value[Age]',
    'Factor Value[Neutral Status]',
    'Factor Value[ER status]',
    'Factor Value[HER2 status]',
    'Factor Value[Intercurrent tumors]',
    'Factor Value[Breed]'
]

In [8]:
samples_clean = samples[cols_importantes]

In [9]:
samples_clean.head(10)

,Source Name,Factor Value[Sex],Factor Value[Tumor state],Factor Value[Tumor grade],Factor Value[Age],Factor Value[Neutral Status],Factor Value[ER status],Factor Value[HER2 status],Factor Value[Intercurrent tumors],Factor Value[Breed]
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle
5,16K-096,Female,Malignant,2.0,144,Neutered,Positive,Positive,simple adenoma (1site),Yorkshire Terrier
6,16K-097,Female,Malignant,1.0,180,Neutered,Positive,Positive,NaN,Maltese
7,16K-099,Female,Malignant,1.0,144,Intact,Positive,Positive,Complex adenoma (1site),Maltese
8,16K-100,Female,Malignant,1.0,168,Intact,Positive,Positive,"Carcinoma in benign tumor (grade 1) (1site), B...",Cocker Spaniel
9,16K-105,Female,Malignant,3.0,144,Neutered,Negative,Positive,NaN,Mixed Breed

In [10]:
samples_clean = samples_clean.rename(columns={
    'Source Name': 'sample_id',
    'Factor Value[Sex]': 'sex',
    'Factor Value[Tumor state]': 'tumor_state',
    'Factor Value[Tumor grade]': 'tumor_grade',
    'Factor Value[Age]': 'age',
    'Factor Value[Neutral Status]': 'neutered',
    'Factor Value[ER status]': 'er_status',
    'Factor Value[HER2 status]': 'her2_status',
    'Factor Value[Intercurrent tumors]': 'tumor_type',
    'Factor Value[Breed]': 'breed'
})

In [11]:
samples_clean.head(10)

,sample_id,sex,tumor_state,tumor_grade,age,neutered,er_status,her2_status,tumor_type,breed
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle
5,16K-096,Female,Malignant,2.0,144,Neutered,Positive,Positive,simple adenoma (1site),Yorkshire Terrier
6,16K-097,Female,Malignant,1.0,180,Neutered,Positive,Positive,NaN,Maltese
7,16K-099,Female,Malignant,1.0,144,Intact,Positive,Positive,Complex adenoma (1site),Maltese
8,16K-100,Female,Malignant,1.0,168,Intact,Positive,Positive,"Carcinoma in benign tumor (grade 1) (1site), B...",Cocker Spaniel
9,16K-105,Female,Malignant,3.0,144,Neutered,Negative,Positive,NaN,Mixed Breed

In [12]:
for col in metabolites.columns:
    print(col)

database_identifier
chemical_formula
smiles
inchi
metabolite_identification
chemical_shift
multiplicity
taxid
species
database
database_version
reliability
uri
search_engine
search_engine_score
smallmolecule_abundance_sub
smallmolecule_abundance_stdev_sub
smallmolecule_abundance_std_error_sub
16K-008_CrAdj
16K-021_CrAdj
16K-030_CrAdj
16K-031_CrAdj
16K-033_CrAdj
16K-070_CrAdj
16K-072_CrAdj
16K-074_CrAdj
16K-077_CrAdj
16K-092_CrAdj
16K-096_CrAdj
16K-097_CrAdj
16K-099_CrAdj
16K-100_CrAdj
16K-103_CrAdj
16K-105_CrAdj
16K-106_CrAdj
16K-107_CrAdj
16K-108_CrAdj
16K-112_CrAdj
16K-114_CrAdj
16K-116_CrAdj
16K-121_CrAdj
16K-129_CrAdj
16K-136_CrAdj
16K-142_CrAdj
16K-149_CrAdj
16K-153_CrAdj
16K-158_CrAdj
16K-162_CrAdj
16K-183_CrAdj
16K-188_CrAdj
16K-190_CrAdj
16K-197_CrAdj
16K-215_CrAdj
16K-217_CrAdj
16K-227_CrAdj
16K-231_CrAdj
16K-233_CrAdj
16K-234_CrAdj
16K-239_CrAdj
16K-242_CrAdj
16K-250_CrAdj
16K-252_CrAdj
16K-262_CrAdj
16K-263_CrAdj
16K-271_CrAdj
16K-276_CrAdj
16K-278_CrAdj
16K-283_CrAdj
16K-290_CrAdj
16K-292_CrAdj
16K-301_CrAdj
16K-306_CrAdj
16K-307_CrAdj
16K-308_CrAdj
16K-311_CrAdj
16K-317_CrAdj
16K-318_CrAdj
16K-319_CrAdj
16K-321_CrAdj
16K-336_CrAdj
16K-340_CrAdj
16K-348_CrAdj
16K-351_CrAdj
16K-353_CrAdj
16K-354_CrAdj
16K-360_CrAdj
16K-365_CrAdj
16K-374_CrAdj
16K-381_CrAdj
16K-400_CrAdj
16K-402_CrAdj
16K-405_CrAdj
16K-414_CrAdj
16K-435_CrAdj
16K-436_CrAdj
16K-439_CrAdj
16K-440_CrAdj
16K-442_CrAdj
16K-452_CrAdj
16K-456_CrAdj
16K-458_CrAdj
16K-471_CrAdj
16K-476_CrAdj
16K-493_CrAdj
16K-496_CrAdj
16K-505_CrAdj
16K-522_CrAdj
16K-577_CrAdj
16K-581_CrAdj
16K-601_CrAdj
16K-606_CrAdj
16K-615_CrAdj
16K-630_CrAdj
16K-634_CrAdj
16K-638_CrAdj
16K-642_CrAdj
16K-644_CrAdj
16K-651_CrAdj
16K-667_CrAdj
16K-678_CrAdj
16K-685_CrAdj
16K-686_CrAdj
16K-688_CrAdj
16K-695_CrAdj
16K-711_CrAdj
16K-719_CrAdj
16K-724_CrAdj
16K-725_CrAdj
16K-730_CrAdj
16K-737_CrAdj
16K-743_CrAdj
16K-755_CrAdj
16K-756_CrAdj
16K-771_CrAdj
16K-785_CrAdj
N-1_CrAdj
N-10_CrAdj
N-11_CrAdj
N-12_CrAdj
N-13_CrAdj
N-14_CrAdj
N-15_CrAdj
N-16_CrAdj
N-17_CrAdj
N-18_CrAdj
N-19_CrAdj
N-2_CrAdj
N-20_CrAdj
N-21_CrAdj
N-22_CrAdj
N-23_CrAdj
N-24_CrAdj
N-25_CrAdj
N-26_CrAdj
N-27_CrAdj
N-28_CrAdj
N-29_CrAdj
N-3_CrAdj
N-30_CrAdj
N-31_CrAdj
N-32_CrAdj
N-33_CrAdj
N-34_CrAdj
N-35_CrAdj
N-36_CrAdj
N-37_CrAdj
N-38_CrAdj
N-39_CrAdj
N-40_CrAdj
N-41_CrAdj
N-42_CrAdj
N-43_CrAdj
N-44_CrAdj
N-45_CrAdj
N-46_CrAdj
N-47_CrAdj
N-48_CrAdj
N-49_CrAdj
N-5_CrAdj
N-50_CrAdj
N-6_CrAdj
N-7_CrAdj
N-8_CrAdj
N-9_CrAdj

In [13]:
metabolites_ml = metabolites[['metabolite_identification']].copy()

In [14]:
sample_cols = [c for c in metabolites.columns if "_CrAdj" in c]

metabolites_ml = metabolites[['metabolite_identification'] + sample_cols]

In [15]:
metabolites_ml = metabolites_ml.set_index('metabolite_identification')

In [16]:
metabolites_ml = metabolites_ml.T

In [17]:
metabolites_ml = metabolites_ml.reset_index()
metabolites_ml = metabolites_ml.rename(columns={'index': 'sample_id'})

In [18]:
metabolites_ml['sample_id'] = metabolites_ml['sample_id'].str.replace('_CrAdj','')

In [19]:
dataset_final = pd.merge(
    samples_clean,
    metabolites_ml,
    on="sample_id",
    how="inner"
)

In [20]:
print(dataset_final.shape)
dataset_final.head()

(166, 66)

,sample_id,sex,tumor_state,tumor_grade,age,neutered,er_status,her2_status,tumor_type,breed,...,Tyramine,Urea,Valine,Xylose,cis-Aconitate,myo-Inositol,sn-Glycero-3-phosphocholine,trans-Aconitate,pi-Methylhistidine,Creatinine
0,16K-008,Female,Malignant,1.0,144,Intact,Positive,Positive,simple carcinoma (grade 1),Chihuahua,...,41.828180,5618.197662,1.953184,12.710718,57.904384,15.204784,6.009796,6.460531,107.635446,NaN
1,16K-021,Female,Malignant,1.0,192,Neutered,Not Available,Not Available,NaN,Maltese,...,41.204573,5978.075414,3.327077,8.189729,94.949667,28.749360,9.298754,8.104419,119.262924,NaN
2,16K-030,Female,Malignant,1.0,156,Intact,Not Available,Not Available,NaN,Maltese,...,28.965580,4878.225400,4.124845,23.099134,58.114487,9.120491,8.937165,6.416426,125.532792,NaN
3,16K-072,Female,Malignant,2.0,144,Intact,Positive,Positive,NaN,Mixed Breed,...,16.386855,8937.220932,4.107876,9.644579,43.534560,17.369173,6.786926,8.260404,175.120557,NaN
4,16K-077,Female,Malignant,3.0,168,Intact,Negative,Negative,NaN,Beagle,...,59.016122,2439.305400,2.610966,8.744664,33.113681,7.915786,15.292801,4.558830,150.109826,NaN

In [22]:
for col in dataset_final.columns:
    print(col)

sample_id
sex
tumor_state
tumor_grade
age
neutered
er_status
her2_status
tumor_type
breed
1-Methylnicotinamide
2-Hydroxybutyrate
2-Hydroxyisobutyrate
2-Oxoisocaproate
2-Phenylpropionate
3-Hydroxyisovalerate
3-Indoxylsulfate
3-Methyl-2-oxovalerate
4-Hydroxyphenylacetate
Acetate
Acetone
Alanine
Allantoin
Betaine
Carnitine
Choline
Citrate
Creatine
Dimethylamine
Formate
Fumarate
Glucose
Glycerol
Glycine
Guanidoacetate
Hippurate
Histidine
Isoleucine
Isopropanol
Kynurenate
Lactate
Mannose
Methanol
Methylamine
Methylguanidine
N,N-Dimethylglycine
N-Phenylacetylglycine
O-Phosphocholine
Propylene glycol
Pyruvate
Succinate
Taurine
Threonine
Trigonelline
Trimethylamine
Tryptophan
Tyramine
Urea
Valine
Xylose
cis-Aconitate
myo-Inositol
sn-Glycero-3-phosphocholine
trans-Aconitate
pi-Methylhistidine
Creatinine